<a href="https://colab.research.google.com/github/Sovarna/Phyton-Assignement/blob/main/Development_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Development Notebook

#Pseudocode

Pseudocode is writing the code in an english based syntax to understand and showcase the logic behind the use of the code. It have it easier to identify problems or any missing steps that is preventing the operation to be successful.\
Thus, below a there are the pseudocode explanation of all the codes i have used in my Business Report.

import sqlite3 
- Sqlite 3 library is used to establish connection with the database and execute data


import pandas as pd 
- Pandas library is used for the analysis of data and processing and also pd represents the alias of the library.


 connect = sqlite3.connect("enron.db")
-This function is used to connect with the Eron database with sqlite3 that is stored in the variable connect.


cur = connect.cursor() 
-  Cursor is used to retrive data and run queries using sql from the database stored in the cur variable.


sql = """
SELECT name
FROM sqlite_master
WHERE type = 'table';
"""
 - SQl query is used to extract the data from the database where name from the database is selected from the sqlite_master displaying the table dataframe. It is stored in the variable SQL.


cur.execute(sql)
 - The cursor is used to generate the sql statement.


cur.fetchall()
 - Fetching the rows of the query


table_df = pd.read_sql_query(sql,connect)
table_df
- Reading and executing the result from the 'sql,connect' that is stored in the variable table_df by connecting with the Eron database and displaying name from the table dataframe 


sql2 = """
PRAGMA table_info('employeelist');
"""
- The Function PRAGMA is use to extract the of employeelist dataframe from the table_info. It is stored in the variable sql2.


cur.execute(sql2)
- Generate employeelist from sql2 statement


cur.fetchall()
- Fetching the rows of sql2 query


employee_df = pd.read_sql_query(sql2,connect)
employee_df
-  Reading and executing by reading the result from the 'sql2,connect' that is stored in the variable employee_df displaying employeelist dataframe from the table_info 


SQL = """
SELECT * From Employeelist
LIMIT 12;
"""
- SQl query is used to extract all employeelist data which are eid, firstName, LastName, Email_id, Email2, Email3, Email4, folder and status from the dataframe with a limit of 12 displayed information. It is stored in the variable SQL.


cur.execute(SQL)
- Executing the employeelist of the SQL query statement.


employee_df = pd.read_sql_query(SQL,connect)
employee_df
- Displaying the table of the sql query by connecting and executing employeelist dataframe from the Eron database


sql3 = """
PRAGMA table_info('message');
"""
- The Function PRAGMA is use to extract the dataframe of messages from the table_info.


cur.execute(sql3)
- Generate message from sql3 statement


cur.fetchall()
- Fetching the rows of sql3 query


message_df = pd.read_sql_query(sql3,connect)
message_df
- Reading and executing the result from the 'sql3,connect' that is stored in the variable message_df displaying message dataframe from the table_info 


SQL = """
SELECT * FROM message 
Limit 12;
"""
- SQl query is used to extract all message data which are mid, sender, date, message_id, subject, body and folder from the dataframe with a limit of 12 displayed information. It is tored in the variable SQL. 


cur.execute(SQL)
- Executing the employeelist of the SQL query statement


message_df = pd.read_sql_query(SQL,connect)
message_df
- Displaying the table of the sql query by connecting and executing message dataframe from the Eron database


sql4 = """
PRAGMA table_info('Recipientinfo');
"""
- The Function PRAGMA is use to extract the dataframe of Recipientinfo from the table_info.It has a variable name of sql4


cur.execute(sql4)
- Generate Recipientinfo from sql4 statement.


cur.fetchall()
- Fetching the rows of sql4 query


Recipientinfo_df = pd.read_sql_query(sql4,connect)
Recipientinfo_df
- Reading and executing the result from the 'sql4,connect' stored in the variable recipientinfo_df displaying Recipientinfo dataframe from the table_info 


SQL = """
SELECT * FROM Recipientinfo
limit 12;
"""
- SQl query is used to extract all Recipientinfo data which are rid, mid, rtype and dater from the dataframe with a limit of 12 displayed information. It has a SQL variable name.


cur.execute(SQL)
- Executing the Recipientinfo of the SQL query statement.


Recipientinfo_df = pd.read_sql_query(SQL,connect)
Recipientinfo_df
- Displaying the table of the sql query by connecting and executing Recipientinfo dataframe from the Eron database.


sql5 = """
PRAGMA table_info('Referenceinfo');
"""
- The Function PRAGMA is use to extract the dataframe of Referenceinfo from the table_info.


cur.execute(sql5)
- Generate Referenceinfo from sql5 statement.


cur.fetchall()
- Fetching the rows of sql5 query


Referenceinfo_df = pd.read_sql_query(sql5,connect)
Referenceinfo_df
- Reading and executing the result from the 'sql5,connect' query stored in the variable Referenceinfo_df displaying Referenceinfo dataframe from the table_info


SQL = """
SELECT * FROM Referenceinfo
Limit 12;
"""
- SQl query is used to extract all Referenceinfo data which are rfid, mid and reference from the dataframe with a limit of 12 displayed information.


cur.execute(SQL)
 - Executing the Referenceinfo of the SQL query statement.


Referenceinfo_df = pd.read_sql_query(SQL,connect)
Referenceinfo_df
- Displaying the table of the sql query by connecting and executing Referenceinfo dataframe from the Eron database

## Email Traffic Over Time

 import matplotlib.pyplot as plt
- Matplotlib is a library used for plotting graphs and visualisation 
import matplotlib.pyplot as plt. Plt is as alias.

import seaborn as sns
- Seaborn library is used in accordance to the matplotlib to have more appealing diagrams. sns as alias.

SQL = """
SELECT date FROM message
"""
- SQl query used to extract date from the message dataframe.

message_df = pd.read_sql_query(SQL,connect)
message_df
-  Generating the 'sql,connect' stored in the variable message_df query statement by reading and displaying date form the message dataframe.

SQL = """
SELECT strftime('%Y-%M-%d',date)
AS date,
COUNT(*) AS count FROM message
GROUP BY date
"""
- SQL query to strftime (to formate the date), count and group the number of emails per day from the message dataframe.

cur.execute(SQL)
-  Executing the SQL query.

Daily_message_df = pd.read_sql_query(SQL, connect)
Daily_message_df
- Executing sql query by displaying date and count of emails per day into a dataframe that is stored in the variable Daily_messages_df.

fig = plt.subplots(figsize=(16,8))
- Plotting the line graph for emails per day using matplotlib and seaborn with figure size 16,8

sns.lineplot(x= 'date', y= 'count',data = Daily_message_df)
- The x-axis = date, the y-axis = count and title = Messages per day. This code is use to plot the line graph. 

plt.title('Messages per Day ')
plt.show()
 - This codes displays the title of the graph.
 - It illustrates the line graph for Daily_message_df.

SQL = """
SELECT strftime('%Y-%M'-%w, date)
AS date,
COUNT(*) AS count FROM message
GROUP BY date
"""
- SQL query to strftime (to formate date) count and group the number of emails per week from the message dataframe.

cur.execute(SQL)
- Executing the SQL query

Weekly_message_df = pd.read_sql_query(SQL, connect)
Weekly_message_df
- Executing sql query by displaying date and count of emails per weekly into a dataframe. It is stored in the variable Weekly_message_df.

fig = plt.subplots(figsize=(16,8))
- Plotting the line graph for emails per week using matplotlib and seaborn with figure size 16,8

sns.lineplot(x= 'date', y= 'count',data = Weekly_message_df)
- The x-axis = date, the y-axis = count and title = Messages per week. This code is use to plot the line graph. 

plt.title('Messages per week ')
plt.show()
- This codes displays the title of the graph.
 - It illustrates the line graph for Weekly_message_df.

SQL = """
SELECT strftime('%Y-%M', date)
AS date,
COUNT(*) AS count FROM message
GROUP BY date
"""
- SQL query to strftime (to formate date) count and group the number of emails per month from the message dataframe.

cur.execute(SQL)
- Executing the SQL query

Monthly_message_df = pd.read_sql_query(SQL, connect)
Monthly_message_df
- Executing sql query by displaying date and count of emails per month into a dataframe. It is stored in the variable Monthly_message_df.

fig = plt.subplots(figsize=(16,8))
- Plotting the line graph for emails per month using matplotlib and seaborn with figure size 16,8

sns.lineplot(x= 'date', y= 'count',data= Monthly_message_df)
- This codes displays the title of the graph.
 - It illustrates the line graph.

plt.title('Messages per month ')
plt.show()
- This codes displays the title of the graph.
 - It illustrates the line graph for Monthly_message_df.

#Top Senders and Recipients


SQL = """

SELECT sender As Sender , COUNT(*) As Number_of_Email FROM message
GROUP BY Sender
ORDER BY COUNT(*) DESC
LIMIT 12
"""
- SQl query used to extract, count, group and order frequent sender data from the message dataframe with a limit of 12 displayed information.

cur.execute(SQL)
- Executing the SQL query

F_Esenders_df = pd.read_sql(SQL,connect)
F_Esenders_df 
- Executing sql query by displaying frequent email sender form the dataframe. The 'sql,connect' is stored in the F_senders_df.

fig = plt.subplots(figsize=(20,10))
- Plotting bar chart for top sender using matplotlib and seaborn. The bar chart has a scale of 20,10.

sns.barplot(x= 'Number_of_Email', y= 'Sender',data= F_Esenders_df)
- The x-axis = Number_of_Email, the y-axis = sender and title = Top sender Email. This code is used to plot the bar chart.

plt.title('Top Sender Email')
plt.show()
- This codes displays the title of the graph.
 - It illustrates the bar chart for F_Esenders_df.

 SQL = """
SELECT rvalue As Recipient, COUNT(*) As Number_of_Email FROM Recipientinfo
GROUP BY Recipient
ORDER BY Number_of_Email  DESC
Limit 12;
"""
- SQl query used to extract, count, group and order frequent recipient data from the Recipientinfo dataframe with a limit of 12 information

cur.execute(SQL)
- Executing the SQL query

F_RecipientE_df = pd.read_sql(SQL,connect)
F_RecipientE_df
- Executing sql query by displaying frequent recipient email form the dataframe. The 'sql,connect' is stored in the F_Recipients_df.

fig = plt.subplots(figsize=(20,10))
- Plotting bar chart for top Recipient using matplotlib and seaborn. The bar chart has a scale of 20,10.

sns.barplot(x= 'Number_of_Email', y= 'Recipient',data= F_RecipientE_df)
-The x-axis = Number_of_Email, the y-axis = Recipient and title = Top sender Recipient. This code is used to plot the bar chart.

plt.title('Top Recipient Email')
plt.show()
- This codes displays the title of the graph.
 - It illustrates the bar chart for F_Recipients_df.

# Email distribution by recipient type

 SQL = """
SELECT rtype, COUNT (*) AS RecipientType_num FROM Recipientinfo
GROUP BY rtype
"""
- SQL query to extract, count and group the email distribution of by Recipient type from the Recipientinfo dataframe that consist of the to, bc and bcc. It is stored in the variable SQL

cur.execute(SQL)
 - Executing the SQL query

rtype_dataframe = pd.read_sql(SQL,connect)
rtype_dataframe
- Executing and read the sql query by displaying rtype email distribution form the Recipientinfo which is stored in the variable rtype_dataframe.

P_Rtype = rtype_dataframe['RecipientType_num']/rtype_dataframe['RecipientType_num'].sum()
- This function is for the calculation of the proportion of rtype with the use of arithmetical operations which are division and sum. This operation is stored in the variable P_Rtype.

figure = plt.subplots(figsize=(8,8))
plt.pie(P_Rtype, labels = rtype_dataframe['rtype'], autopct='%.0f%%', startangle=80 )
 - Plotting pie chart for Proportion of emails by each rtype using matplotlib and seaborn and having a figure size of (8,8)
plt.title('Proportion of Emails by each rtype')
plt.show()
 - This codes displays the title of the graph.
 - The pie data is extracted from rtype_dataframe 

fig = plt.subplots(figsize=(5,5))
sns.barplot(x= 'rtype', y= 'RecipientType_num', data= rtype_dataframe)
- Plotting stacked bar for Proportion of emails by each rtype using matplotlib and seaborn. It has a figure size of (5,5).

plt.title('Proportion of Emails by each rtype')
plt.show()
 - This codes displays the title of the graph.
 - The stacked bar data is extracted from rtype_dataframe

### Testing

# Industry Standard

- sql = sql query 

- table_df = table dataframe

- sql2 = sql query 2 for employeelist

- employee_df = employee dataframe

- SQL = SQL for employeelist

- sql3 = sql query 3 for message

- message_df = message dataframe

- SQL = SQL for message

- sql4 = sql query 4 for Recipientinfo

- Recipientinfo_df =Recipient dataframe

- SQL = SQL for Recipientinfo

- sql5 = sql query r for Referenceinfo

- Referenceinfo_df = Referenceinfo 
dataframe

####Email Traffic Over time

- SQL =  query date from message

- Daily_message_df = message per day dataframe

- Weekly_message_df = message per week

- Monthly_message_df = message per month

- fig = figure

####Top senders and Recipients

- SQL = query sender from message

- F_Esenders_df = Frequent Email senders dataframe

- SQL = query Recipient from Recipient info

- F_Recipient_df = Frequent Recipient dataframe.

- fig = figure

####Email distribution by Recipient Type

- SQL = query rtype from Recipientinfo

- rtype_dataframe = recipient type dataframe

- P_Rtype = proportion of recipient type.

- fig = figure